/// Extracted base server URL and optional credentials from an Xtream export
/// link. Credentials may be null when they are not embedded in the URL and are
/// supplied through the provider configuration instead.
class XtreamExportParts {
  final String serverUrl;
  final String? username;
  final String? password;

  const XtreamExportParts({
    required this.serverUrl,
    this.username,
    this.password,
  });
}

/// Detects Xtream panel export links such as
/// `http://host:port/get.php?username=X&password=Y&type=m3u_plus` or
/// `player_api.php` URL variants.
///
/// Many providers distribute their content as a single M3U export generated by
/// an Xtream panel. Downloading that export can be orders of magnitude larger
/// than the panel's JSON API, and some servers refuse to serve it at all.
/// Detecting the panel and syncing through the JSON API is the reliable path.
class XtreamUrlDetector {
  XtreamUrlDetector._();

  /// Returns the parsed server URL when [raw] looks like an Xtream panel
  /// export URL, otherwise `null`. Credentials are parsed only when present.
  static XtreamExportParts? parse(String? raw) {
    if (raw == null) return null;

    var url = raw.trim();
    if (url.isEmpty) return null;
    if (!url.contains('://')) url = 'http://$url';

    final uri = Uri.tryParse(url);
    if (uri == null || uri.host.isEmpty) return null;

    final path = uri.path.toLowerCase();
    final isApiPath =
        path.endsWith('get.php') || path.endsWith('player_api.php');
    if (!isApiPath) return null;

    var serverUrl = '${uri.scheme}://${uri.host}';
    if (uri.hasPort) serverUrl = '$serverUrl:${uri.port}';

    final username = uri.queryParameters['username'];
    final password = uri.queryParameters['password'];

    return XtreamExportParts(
      serverUrl: serverUrl,
      username: (username == null || username.isEmpty) ? null : username,
      password: (password == null || password.isEmpty) ? null : password,
    );
  }

  /// Convenience wrapper around [parse].
  static bool isXtreamExport(String? raw) => parse(raw) != null;
}
