import 'dart:async';

import 'package:get/get.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:stream_hub/core/helpers/profile_key_helper.dart';
import 'package:stream_hub/core/logging/logging_service.dart';
import 'package:stream_hub/core/media/enums/media_source_type.dart';
import 'package:stream_hub/core/media/enums/media_type.dart';
import 'package:stream_hub/data/models/media_item.dart';
import 'package:stream_hub/data/services/active_profile_service.dart';

/// Profile-aware watch-history service backed by Hive.
///
/// History entries are persisted to [historyBox] under keys generated by
/// [ProfileKeyHelper].  On profile switch the in-memory list is reloaded
/// from Hive so each profile sees only its own watch history.
///
/// Key format: `ph_{profileId}/{itemId}` (or bare `itemId` for default profile).
class HistoryService {
  final LoggingService logger;
  final Box? _box;

  // In-memory store — keyed by itemId for O(1) lookup.
  final Map<String, MediaItem> _historyMap = {};
  final Map<String, DateTime> _searchHistory = {};
  final Map<String, int> _providerUsage = {};

  StreamSubscription<String>? _profileSub;

  HistoryService({LoggingService? logger, Box? box})
      : logger = logger ?? LoggingService(),
        _box = box {
    _loadFromBox();
    _listenForProfileChanges();
  }

  // ─── Helpers ───────────────────────────────────────────────────────────────

  String get _profileId {
    if (Get.isRegistered<ActiveProfileService>()) {
      return Get.find<ActiveProfileService>().currentProfileId;
    }
    return '';
  }

  String _key(String itemId) => ProfileKeyHelper.histKey(_profileId, itemId);

  bool _ownsKey(String key) =>
      ProfileKeyHelper.isHistKeyForProfile(key, _profileId);

  // ─── Profile switching ────────────────────────────────────────────────────

  void _listenForProfileChanges() {
    if (!Get.isRegistered<ActiveProfileService>()) return;
    _profileSub?.cancel();
    _profileSub = Get.find<ActiveProfileService>()
        .profileId
        .stream
        .listen((_) => _reloadForProfile());
  }

  void _reloadForProfile() {
    _historyMap.clear();
    _loadFromBox();
    logger.info(
      'HistoryService: reloaded for profile "$_profileId"',
      tag: 'HistoryService',
    );
  }

  // ─── Hive persistence ────────────────────────────────────────────────────

  void _loadFromBox() {
    if (_box == null) return;
    try {
      for (final key in _box.keys) {
        final keyStr = key.toString();
        if (!_ownsKey(keyStr)) continue;
        final raw = _box.get(key);
        if (raw is Map) {
          final item = _mapToMediaItem(raw);
          if (item != null) {
            _historyMap[item.id] = item;
          }
        }
      }
      logger.info(
        'HistoryService: loaded ${_historyMap.length} entries (profile: "$_profileId")',
        tag: 'HistoryService',
      );
    } catch (e) {
      logger.warning(
        'HistoryService: failed to load from box',
        tag: 'HistoryService',
        error: e,
      );
    }
  }

  Future<void> _persist(MediaItem item) async {
    if (_box == null) return;
    try {
      await _box.put(_key(item.id), _mediaItemToMap(item));
    } catch (e) {
      logger.warning(
        'HistoryService: failed to persist entry ${item.id}',
        tag: 'HistoryService',
        error: e,
      );
    }
  }

  // ─── Public API ──────────────────────────────────────────────────────────

  void recordOpened(MediaItem item) {
    final updated = item.copyWith(updatedAt: DateTime.now());
    _historyMap[item.id] = updated;
    _persist(updated);
    logger.info('Recorded opened: ${item.title}', tag: 'HistoryService');
  }

  void recordPlayed(MediaItem item) {
    final updated = item.copyWith(updatedAt: DateTime.now());
    _historyMap[item.id] = updated;
    _persist(updated);
    logger.info('Recorded played: ${item.title}', tag: 'HistoryService');
  }

  void recordFinished(MediaItem item) {
    final updated = item.copyWith(updatedAt: DateTime.now());
    _historyMap[item.id] = updated;
    _persist(updated);
    logger.info('Recorded finished: ${item.title}', tag: 'HistoryService');
  }

  void recordSearch(String query) {
    _searchHistory[query] = DateTime.now();
    logger.info('Recorded search: $query', tag: 'HistoryService');
  }

  void recordProviderUsage(String providerId) {
    _providerUsage[providerId] = (_providerUsage[providerId] ?? 0) + 1;
  }

  List<MediaItem> getHistory() {
    final list = _historyMap.values.toList();
    list.sort((a, b) => b.updatedAt.compareTo(a.updatedAt));
    return list;
  }

  List<String> getRecentSearches({int limit = 10}) {
    final entries = _searchHistory.entries.toList();
    entries.sort((a, b) => b.value.compareTo(a.value));
    return entries.take(limit).map((e) => e.key).toList();
  }

  Map<String, int> getProviderUsage() => Map.unmodifiable(_providerUsage);

  Future<void> clearHistory() async {
    if (_box != null) {
      try {
        final keysToRemove = _box.keys
            .where((k) => _ownsKey(k.toString()))
            .toList();
        await _box.deleteAll(keysToRemove);
      } catch (e) {
        logger.warning(
          'HistoryService: failed to clear box for profile "$_profileId"',
          tag: 'HistoryService',
          error: e,
        );
      }
    }
    _historyMap.clear();
    logger.info('History cleared (profile: "$_profileId")', tag: 'HistoryService');
  }

  void clearSearchHistory() {
    _searchHistory.clear();
    logger.info('Search history cleared', tag: 'HistoryService');
  }

  void dispose() {
    _profileSub?.cancel();
  }

  // ─── Serialization ────────────────────────────────────────────────────────

  Map<String, dynamic> _mediaItemToMap(MediaItem item) => {
        'id': item.id,
        'providerId': item.providerId,
        'providerType': item.providerType.name,
        'mediaType': item.mediaType.name,
        'title': item.title,
        'thumbnail': item.thumbnail,
        'poster': item.poster,
        'createdAt': item.createdAt.millisecondsSinceEpoch,
        'updatedAt': item.updatedAt.millisecondsSinceEpoch,
      };

  MediaItem? _mapToMediaItem(Map raw) {
    try {
      final now = DateTime.now();
      return MediaItem(
        id: raw['id'] as String,
        providerId: raw['providerId'] as String? ?? '',
        providerType: MediaSourceType.values.firstWhere(
          (e) => e.name == (raw['providerType'] as String? ?? ''),
          orElse: () => MediaSourceType.m3u,
        ),
        mediaType: MediaType.values.firstWhere(
          (e) => e.name == (raw['mediaType'] as String? ?? ''),
          orElse: () => MediaType.channel,
        ),
        title: raw['title'] as String? ?? '',
        thumbnail: raw['thumbnail'] as String?,
        poster: raw['poster'] as String?,
        createdAt: raw['createdAt'] != null
            ? DateTime.fromMillisecondsSinceEpoch(raw['createdAt'] as int)
            : now,
        updatedAt: raw['updatedAt'] != null
            ? DateTime.fromMillisecondsSinceEpoch(raw['updatedAt'] as int)
            : now,
      );
    } catch (_) {
      return null;
    }
  }
}